### ISSUE TITLE
Overwrite schedule-based predictions daily, based on newest schedule

### ISSUE THREAD

**Issue by flauschzelle** [dystonse/dystonse-gtfs-data#10]
Currently, we compute and store predictions based on the newest available schedule for 8.5 days into the future. 
New predictions are always based on the newest schedule, but once the 8.5. days is filled up for the first time, this only applies to the time after that, as soon as it comes into scope.

If there are any changes to the schedule, they are currently not included in the predictions for the near future - i.e. the time span we already had made predictions for when the changes went into effect.

This could be fixed by overwriting all schedule-based predictions whenever we get a new schedule, i.e. daily.

**Comment by lenaschimmel** [comment]
I just implemented and deployed this, now we have to wait for results…

**Comment by lenaschimmel** [comment]
There still was a [tiny bug 🐞](https://github.com/dystonse/dystonse-gtfs-data/commit/1ccc420d281326d6004925a9db325da5e63718dd), which is now fixed. Now a new schedule will trigger new schedule based predictions, which will update the old ones, or insert new ones. 

Now we still need to delete the old ones which are not updated because of trip_id changes.
